export const BASE_URL = "http://ws.audioscrobbler.com/2.0";
export const LOADING_MESSAGE = "Loading songs...";
export const ERROR_MESSAGE = "Something Went Wrong!!..."
export const NO_PUBLISH_YEAR = "Sorry, No Info found!!"
export const NO_WIKI = "Sorry, No WIKI found!!";
export const NO_TRACK = "Sorry, No Track found!!";
export const NO_DURATION = "Sorry, No Duration found!!"
export const ARTIST_NAME = "Cher"
export const LASTFM_API_KEY= "4cfef71ffd3f52fd821199660584e61f"